---
- name: three tier
  hosts: all
  become: true
  tasks:
    - name: install nginx
      yum: name=nginx state=present
      when: inventory_hostname in groups ['webtier']
    - name: install php
      yum: name=php8.1 state=present
      when: inventory_hostname in groups ['apptier']
    - name: install database
      yum: name=mariadb105-server state=present
      when: inventory_hostname in groups ['dbtier']
